#+STARTUP: fold indent

* Commentary
1. Good evidence of non-stationarity in factors over time
2. Gold becomes more investment-like over time
3. Credit is a distinct factor (with small variance), once other factors are accounted for

* General approach
1. Assets that strongly load on each factor (by R2)
2. Asset pairs that inversely correlated on each factor (by loading)
3. Idiosyncratic assets (by low communality)

* 2009 Varimax interpretation (n = 30)
Proportional explained variance: [0.432 0.178 0.063 0.04  0.023]
Cumulative explained variance: [0.432 0.61  0.674 0.714 0.736]

** Factors
1. Stocks vs. bonds (~0.432~)
2. US bonds/interest rates (~0.178~)
3. Gold and commodities (~0.063~)
4. Defensive/Real Estate (~0.04~)
5. Energy (~0.023~)

** Idiosyncratic variables (low communality)
#+BEGIN_EXAMPLE
0.74 GLD	SPDR Gold Shares
0.74 GDX	VanEck Gold Miners ETF
0.73 VDC	Vanguard Consumer Staples ETF
0.68 VPU	Vanguard Utilities ETF
0.64 LQD	iShares iBoxx $ Invmt Grade Corp Bd ETF
0.62 DFJ	WisdomTree Japan SmallCap Dividend ETF
0.61 AFK	VanEck Africa ETF
0.55 IDX	VanEck Indonesia ETF
0.52 DBC	Invesco DB Commodity Tracking
0.51 EMB	iShares JP Morgan USD Em Mkts Bd ETF
0.48 SHY	iShares 1-3 Year Treasury Bond ETF
0.41 BWX	SPDR Blmbg Barclays Intl Trs Bd ETF
0.36 VNM	VanEck Vietnam ETF
#+END_EXAMPLE

* 2006 Varimax interpretation (n=23)
Proportional explained variance: [0.433 0.163 0.077 0.047 0.04 ]
Cumulative explained variance: [0.433 0.596 0.673 0.72  0.761]

** Factors
1. Stocks vs. bonds (~0.433~)
2. US bonds/interest rates (~0.163~)
3. Gold and commodities (~0.077~)
4. Energy and commodities (~0.047~)
5. Japan (~0.04~)
6. (US Credit, if you run 6 factors)

** Idiosyncratic variables (low communality)
#+BEGIN_EXAMPLE
0.76 VDC	Vanguard Consumer Staples ETF
0.74 GDX	VanEck Gold Miners ETF
0.67 TIP	iShares TIPS Bond ETF
0.66 AGG	iShares Core US Aggregate Bond ETF
0.65 VGSIX	Vanguard Real Estate Index Investor
0.60 VPU	Vanguard Utilities ETF
0.57 DBC	Invesco DB Commodity Tracking
0.57 DFJ	WisdomTree Japan SmallCap Dividend ETF
0.46 SHY	iShares 1-3 Year Treasury Bond ETF
0.45 LQD	iShares iBoxx $ Invmt Grade Corp Bd ETF
#+END_EXAMPLE

* 2004 Varimax interpretation (n = 19)
Proportional explained variance: [0.469 0.204 0.044 0.028 0.018]
Cumulative explained variance: [0.469 0.673 0.717 0.745 0.763]

** Factors
1. Stocks vs. bonds (~0.469~)
2. US bonds/interest rates (~0.204~)
3. Foreign/gold/energy (~0.044~)
4. US credit (~0.028~)
5. Defensive (~0.018~)

** Idiosyncratic variables (low communality)
#+BEGIN_EXAMPLE
0.69 VDE	Vanguard Energy ETF
0.68 TIP	iShares TIPS Bond ETF
0.68 LQD	iShares iBoxx $ Invmt Grade Corp Bd ETF
0.68 AGG	iShares Core US Aggregate Bond ETF
0.64 VPU	Vanguard Utilities ETF
0.64 VGSIX	Vanguard Real Estate Index Investor
0.52 SHY	iShares 1-3 Year Treasury Bond ETF
0.19 GLD	SPDR Gold Shares
#+END_EXAMPLE

* 1998 Varimax interpretation (n = 13)
N is too low
Proportional explained variance: [0.335 0.306 0.136 0.02  0.01 ]
Cumulative explained variance: [0.335 0.641 0.777 0.797 0.807]

** Factors
1. Bonds (~0.335~)
2. Stocks (~0.306~)
3. Foreign stocks (~0.136~)
4. Long vs short interest rates (~0.02~)
5. US large cap (~0.01~)

* Data set
1. Rolling daily correlations - converging on 70 trading days window as stable but informative
2. Annualized variance

* Cast net more widely for different kinds of funds
1. market sector (2004)
   VDC VDE VAW VPU
2. defense (2005)
   PPA
3. miners (2006)
   GDX
4. Frontier country funds (2009)
   AFK IDX VNM
5. min var, min vol (2011)
   USMV SPLV

* Co-linear with IVV
1. value
   VIVAX
2. growth
   VIGRX
3. dividends (2006)
   VIG VDIGX VYM
4. dividend aristocrats (2013)
   NOBL
5. quality (2013)
   QUAL

* Asset Universe
** "12 Assets" whitepaper
SPY ETF extended with S&P 500 Index
VGK ETF extended with S&P Europe BMI
VPL ETF extended with S&P Asia Pacific BMI
VWO ETF extended with S&P Emerging BMI
IEF ETF extended with S&P US Treasury 7-10 Year TR Index
TLT ETF exteneded with S&P US Treasury Bond 20+ Year TR Index
LTPZ extended with S&P US TIPS 15+ Year Index and PIMCO Real Return Fund
BWX ETF extended with S&P/Citigroup International Treasury Ex-US TR Index and T. Rowe Price International Bond Fund
EMB ETF extended with PIMCO Emerging Markets Bond Fund and T. Rowe Price Emerging Markets Bond Fund
DBC ETF extended with Deutsche Bank Liquid Commodity Index
RWO ETF extended with Cohen & Steers Global Realty Shares,Inc. Class I
GLD ETF extended with spot gold in USD
** Pre-loaded assets in portfoliovisualizer.com
IVV iShares Core S&P 500 ETF
IJH iShares Core S&P Mid-Cap ETF
IJR iShares Core S&P Small-Cap ETF
EFA iShares MSCI EAFE ETF
SCZ iShares MSCI EAFE Small-Cap ETF
EEM iShares MSCI Emerging Markets ETF
AGG iShares Core US Aggregate Bond ETF
SHY iShares 1-3 Year Treasury Bond ETF
IEF iShares 7-10 Year Treasury Bond ETF
TLT iShares 20+ Year Treasury Bond ETF
TIP iShares TIPS Bond ETF
LQD iShares iBoxx $ Invmt Grade Corp Bd ETF
VNQ Vanguard Real Estate ETF
GLD SPDR Gold Shares
DBC Invesco DB Commodity Tracking
** Combined list (12 Assets + Portfolio Visualizer)
*** Extant from 2009
AGG BWX DBC EEM EFA EMB GLD IEF IJH IJR IVV LQD LTPZ RWO SCZ SHY TIP TLT VGK VNQ VPL VWO
*** Extant form 2009, old tickers
AGG BWX DBC EEM EFA EMB GLD IEF IJH IJR IVV LQD LTPZ RWO SCZ SHY TIP TLT VEURX VGSIX VPACX VEIEX
*** Extant from 2004 (includes GLD)
AGG EEM EFA GLD IEF IJH IJR IVV LQD SHY TIP TLT VEURX VGSIX VPACX VEIEX
** Additional assets
1. First set
   FIASX VFSNX BWX DFJ VPU VDC
** Co-Linear substitutes, ranked
*** International small cap
1. SCZ (2009)
2. VFSNX
3. FIASX (2006)
*** Emerging
1. EEM
2. VEIEX (no Korea)
*** Developed large cap
1. VEURX
2. EFA
*** US small/mid cap (if necessary)
1. IJR
2. IJH
** Complete asset list
We are using set 2, which is more comprehensive.
*** Total 2009, old tickers
1. AGG BWX DBC DFJ EEM EFA EMB FIASX GLD IEF IJH IJR IVV LQD LTPZ RWO SCZ SHY TIP TLT VDC VEIEX VEURX VFSNX VGSIX VPACX VPU
2. AFK AGG BWX DBC DFJ EEM EMB GDX GLD IDX IEF IJR IJH IVV LQD LTPZ PPA RWO SCZ SHY TIP TLT VAW VDC VDE VEURX VGSIX VNM VPACX VPU
*** Total 2006, old tickers (includes DFJ)
1. AGG DBC DFJ EEM EFA FIASX GLD IEF IJH IJR IVV LQD SHY TIP TLT VDC VEIEX VEURX VGSIX VPACX VPU
2. AGG DBC DFJ EEM FIASX GDX GLD IEF IJR IJH IVV LQD PPA SHY TIP TLT VAW VDC VDE VEURX VGSIX VPACX VPU
*** Total 2004, old tickers (includes GLD)
1. AGG EEM EFA FIASX GLD IEF IJH IJR IVV LQD SHY TIP TLT VDC VEIEX VEURX VGSIX VPACX VPU
2. AGG EEM FIASX GLD IEF IJR IJH IVV LQD SHY TIP TLT VAW VDC VDE VEURX VGSIX VPACX VPU
